Bugfix/aos 3421
Skatteetaten/sprocket pull request #6
Opened 2019-05-15 10:00 UTC by bjartek

2019-05-16 12:00 UTC, jarlehansen requested changes

2019-05-16 12:00 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/sprocket/service/ImageChangeEventService.kt
>          logger.debug("Parsed=$globalEventPayload")
kan skrives `logger.debug { "Parsed=$globalEventPayload" }`

2019-05-16 12:00 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/sprocket/service/ImageChangeEventService.kt
> +        if (imageInfo.repository.contains("proxy")) {
hva med å lage 2 funksjoner på ImageInfo:
1) isProxy eller noe sånt
2) sha256 (vet ikke helt hva denne skal hete)

Bruke begge i en if-statement

2019-05-16 12:00 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/sprocket/service/ImageChangeEventService.kt
> +        val (group, name, version) = imageInfo.name
flytte uthentingen inn i imageInfo?

2019-05-16 12:00 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/sprocket/service/OpenShiftService.kt
> +            logger.info("Found items={} imagestreams", it.count())
`logger.info { ... }`

2019-05-16 12:00 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/sprocket/service/OpenShiftServiceTest.kt
> +            val response = service.importImage(imageStream, url)
shadowed navn, rename til importImageResponse feks?

2022-01-26 09:49 UTC, closed without merging

2022-01-26 09:49 UTC, stromland commented
En komponent som ikke er prioritert å jobbe med.